library(checkpoint)
checkpoint("2015-09-30")

library(reshape2)
library(plyr)
library(dplyr)
library(ggplot2)
library(gmodels)
library(car)
library(lubridate)
library(scales)
library(proto)
library(grid)
library(gridExtra)

.libPaths("/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library(HIEv)
